---
title: "RSVI"
author: "Paula and Beni"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
# output:
#   pdf_document:
#     toc: true
#     toc_depth: 2
header-includes:
   - \usepackage{amsmath}
# bibliography: bibliography.bib
---

```{r}
source("remove_outliers.R")
source("gather_data.R")
source("align_events.R")
source("plot_rsvi.R")
source("plot_compare.R")
source("rsvi_sites.R")

library(dplyr)
library(lubridate)
library(readr)
library(ggplot2)
```

## Gather data

Load all data.
```{r}
ddf <- gather_data("/alphadata01/bstocker/data/modis_MOD09GA1km_fluxnet_cutouts/MOD09GA_MODOCGA_filter_indices.RData") %>% 
  ungroup()
```

Subset homogenous sites. Selection of sites is based on whether sites could be allocated to clusters in Stocker et al. (2018) and based on the selection by Manuela Balzarolo (see `site_selection_rsvi.Rmd`).
```{r}
df_homo <- read_csv("./data/sites.csv")
ddf <- ddf %>% filter( site %in% df_homo$sitename )
```

### Align by drought event

```{r}
## Get fLUE Stocker et al., 2018 publicly available data here: https://zenodo.org/record/1158524#.W_bNMZNKjOQ
df_flue <- readr::read_csv( "/alphadata01/bstocker/data/flue/flue_stocker18nphyt.csv" ) %>% 
  dplyr::select(-year, -doy, -cluster) %>% 
  dplyr::rename( isevent = is_flue_drought )

## Rearrange data. Function returns list( df_dday, df_dday_aggbydday )
dovars <- colnames( dplyr::select( ddf, -date, -site ) ) # this does not necessarily work with the data's column names you have in 'ddf'

# dovars <- colnames(ddf)[3:14]
out_align <- align_events( ddf, df_flue, dovars, leng_threshold = 10, before=20, after=60, nbins=8, do_norm=TRUE )

## plot what you got with aligned data (median)
out_align$df_dday_aggbydday %>% 
  ggplot(aes(x=dday, y=evi_median)) +
  geom_line()
```

### Make plots

```{r}
plot_compare( out_align$df_dday_aggbydday, scale = FALSE, method = "zscore" )

# One site
out <- plot_rsvi_bysite( "FR-Pue", ddf )
rsvi_sites(out_align$df_dday, name_site="FR-Pue")
```
