---
title: "RSVI"
author: "Paula and Beni"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
# output:
#   pdf_document:
#     toc: true
#     toc_depth: 2
header-includes:
   - \usepackage{amsmath}
# bibliography: bibliography.bib
---

```{r}
source("remove_outliers.R")
source("gather_data_v2.R")
source("align_events.R")
source("plot_rsvi.R")
source("plot_compare.R")
source("rsvi_sites.R")
library(dplyr)
library(lubridate)
library(readr)
```

## Gather data

```{r}
source("remove_outliers.R")
ddf <- gather_data_v2() %>% ungroup()

## Get additional information for the sites
load("data/metainfo_sites_fluxnet2015.Rdata")
```

### Align by drought event

```{r}
require(dplyr)
## Get fLUE Stocker et al., 2018 publicly available data here: https://zenodo.org/record/1158524#.W_bNMZNKjOQ
df_flue <-  readr::read_csv("data/flue_stocker18nphyt.csv") %>% 
  dplyr::select(-year, -doy, -cluster) %>% 
  dplyr::rename( isevent = is_flue_drought )

## Get homogeneous sites:
homo_sites <- read.csv("data/homogenous_sites.csv") %>% 
  rename(site = sitename)  
homo_sites <- as.character(unique(homo_sites$site))

ddf <- ddf[which(ddf$site %in% homo_sites),] %>% ungroup()

## Rearrange data. Function returns list( df_dday, df_dday_aggbydday )
dovars <- colnames( dplyr::select( ddf, -date, -site ) ) # this does not necessarily work with the data's column names you have in 'ddf'
# dovars <- colnames(ddf)[3:14]
out_align <- align_events(ddf, df_flue, dovars, leng_threshold = 10, before=20, after=60, nbins=8, do_norm=TRUE )

## plot what you got with aligned data (median)
with(out_align$df_dday_aggbydday, plot(dday, evi_median, type="l" ))
```

### Make plots

```{r}
plot_compare(out_align$df_dday_aggbydday, scale = FALSE, method = "zscore")
# One site
out <- plot_rsvi_bysite( "FR-Pue", ddf )
rsvi_sites(df_dday, name_site="FR-Pue")
```
